/opt/_internal/cpython-2.7.15-ucs4/lib/python2.7/site-packages/paddle/fluid/clip.py:779: UserWarning: Caution! 'set_gradient_clip' is not recommended and may be deprecated in future! We recommend a new strategy: set 'grad_clip' when initializing the 'optimizer'. This method can reduce the mistakes, please refer to documention of 'optimizer'.
  warnings.warn("Caution! 'set_gradient_clip' is not recommended "
2020-12-25 11:59:07,425-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
/opt/_internal/cpython-2.7.15-ucs4/lib/python2.7/site-packages/paddle/fluid/clip.py:779: UserWarning: Caution! 'set_gradient_clip' is not recommended and may be deprecated in future! We recommend a new strategy: set 'grad_clip' when initializing the 'optimizer'. This method can reduce the mistakes, please refer to documention of 'optimizer'.
  warnings.warn("Caution! 'set_gradient_clip' is not recommended "
2020-12-25 12:00:44,873-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
2020-12-25 12:00:50,081-ERROR: Config dataset_dir dataset/coco is not exits!
2020-12-25 12:00:50,081-WARNING: Config annotation dataset/coco/annotations/instances_val2017.json is not a file, dataset config is not valid
2020-12-25 12:00:50,081-INFO: Dataset /root/paddlejob/workspace/ppyolo/PaddleDetection/dataset/coco is not valid for reason above, try searching /root/.cache/paddle/dataset or downloading dataset...
2020-12-25 12:00:50,081-INFO: Downloading train2017.zip from http://images.cocodataset.org/zips/train2017.zip
Traceback (most recent call last):
  File "tools/train.py", line 372, in <module>
    main()
  File "tools/train.py", line 148, in main
    eval_reader = create_reader(cfg.EvalReader, devices_num=1)
  File "/root/paddlejob/workspace/ppyolo/PaddleDetection/ppdet/data/reader.py", line 441, in create_reader
    reader = Reader(**cfg)()
  File "/root/paddlejob/workspace/ppyolo/PaddleDetection/ppdet/data/reader.py", line 210, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/root/paddlejob/workspace/ppyolo/PaddleDetection/ppdet/data/source/dataset.py", line 65, in get_roidb
    self.image_dir)
  File "/root/paddlejob/workspace/ppyolo/PaddleDetection/ppdet/utils/download.py", line 142, in get_dataset_path
    get_path(url, data_dir, md5sum, check_exist)
  File "/root/paddlejob/workspace/ppyolo/PaddleDetection/ppdet/utils/download.py", line 212, in get_path
    fullname = _download(url, root_dir, md5sum)
  File "/root/paddlejob/workspace/ppyolo/PaddleDetection/ppdet/utils/download.py", line 288, in _download
    req = requests.get(url, stream=True)
  File "/opt/_internal/cpython-2.7.15-ucs4/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/_internal/cpython-2.7.15-ucs4/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/_internal/cpython-2.7.15-ucs4/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/_internal/cpython-2.7.15-ucs4/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/_internal/cpython-2.7.15-ucs4/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='images.cocodataset.org', port=80): Max retries exceeded with url: /zips/train2017.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe4d2be4a50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
/opt/_internal/cpython-2.7.15-ucs4/lib/python2.7/site-packages/paddle/fluid/clip.py:779: UserWarning: Caution! 'set_gradient_clip' is not recommended and may be deprecated in future! We recommend a new strategy: set 'grad_clip' when initializing the 'optimizer'. This method can reduce the mistakes, please refer to documention of 'optimizer'.
  warnings.warn("Caution! 'set_gradient_clip' is not recommended "
2020-12-25 12:02:35,637-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
loading annotations into memory...
Done (t=0.89s)
creating index...
index created!
2020-12-25 12:02:42,838-INFO: places would be ommited when DataLoader is not iterable


API is deprecated since 2.0.0 Please use FleetAPI instead.
WIKI: https://github.com/PaddlePaddle/Fleet/blob/develop/markdown_doc/transpiler

        
W1225 12:02:43.060084 39116 device_context.cc:252] Please NOTE: device: 6, CUDA Capability: 70, Driver API Version: 10.2, Runtime API Version: 10.0
W1225 12:02:43.068136 39116 device_context.cc:260] device: 6, cuDNN Version: 7.6.
E1225 12:02:46.691053289   39329 server_chttp2.cc:38]        {"created":"@1608868966.691014431","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":305,"referenced_errors":[{"created":"@1608868966.691011266","description":"Unable to configure socket","fd":57,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":202,"referenced_errors":[{"created":"@1608868966.691005376","description":"OS Error","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":175,"os_error":"Address already in use","syscall":"bind"}]}]}
W1225 12:02:46.691109 39329 grpc_server.cc:483] Server listening on 127.0.0.1:11735 failed, selected port: 0, retry after 3 seconds!
E1225 12:02:49.691388590   39329 server_chttp2.cc:38]        {"created":"@1608868969.691345744","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":305,"referenced_errors":[{"created":"@1608868969.691341566","description":"Unable to configure socket","fd":57,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":202,"referenced_errors":[{"created":"@1608868969.691335178","description":"OS Error","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":175,"os_error":"Address already in use","syscall":"bind"}]}]}
W1225 12:02:49.691431 39329 grpc_server.cc:483] Server listening on 127.0.0.1:11735 failed, selected port: 0, retry after 3 seconds!
E1225 12:02:52.691703444   39329 server_chttp2.cc:38]        {"created":"@1608868972.691666685","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":305,"referenced_errors":[{"created":"@1608868972.691661869","description":"Unable to configure socket","fd":57,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":202,"referenced_errors":[{"created":"@1608868972.691655167","description":"OS Error","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":175,"os_error":"Address already in use","syscall":"bind"}]}]}
W1225 12:02:52.691746 39329 grpc_server.cc:483] Server listening on 127.0.0.1:11735 failed, selected port: 0, retry after 3 seconds!
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::distributed::AsyncGRPCServer::StartServer()

----------------------
Error Message Summary:
----------------------
Error: can't bind to address:127.0.0.1:11735
  [Hint: Expected selected_port_ != 0, but received selected_port_:0 == 0:0.] at (/paddle/paddle/fluid/operators/distributed/grpc/grpc_server.cc:491)

W1225 12:02:55.698451 39329 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1225 12:02:55.698472 39329 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1225 12:02:55.698475 39329 init.cc:231] The detail failure signal is:

W1225 12:02:55.698480 39329 init.cc:234] *** Aborted at 1608868975 (unix time) try "date -d @1608868975" if you are using GNU date ***
W1225 12:02:55.700002 39329 init.cc:234] PC: @                0x0 (unknown)
W1225 12:02:55.700057 39329 init.cc:234] *** SIGABRT (@0x98cc) received by PID 39116 (TID 0x7f7210b92700) from PID 39116; stack trace: ***
W1225 12:02:55.701193 39329 init.cc:234]     @     0x7f7281e067e0 (unknown)
W1225 12:02:55.702387 39329 init.cc:234]     @     0x7f728140a4f5 __GI_raise
W1225 12:02:55.703534 39329 init.cc:234]     @     0x7f728140bcd5 __GI_abort
W1225 12:02:55.704360 39329 init.cc:234]     @     0x7f726ecff572 __gnu_cxx::__verbose_terminate_handler()
W1225 12:02:55.705202 39329 init.cc:234]     @     0x7f726ecfd456 __cxxabiv1::__terminate()
W1225 12:02:55.706173 39329 init.cc:234]     @     0x7f726ecfd491 std::terminate()
W1225 12:02:55.707074 39329 init.cc:234]     @     0x7f726ecfd6d3 __cxa_throw
W1225 12:02:55.708932 39329 init.cc:234]     @     0x7f722a38a035 paddle::operators::distributed::AsyncGRPCServer::StartServer()
W1225 12:02:55.709868 39329 init.cc:234]     @     0x7f726ed2dcd0 execute_native_thread_routine_compat
W1225 12:02:55.710981 39329 init.cc:234]     @     0x7f7281dfeaa1 start_thread
W1225 12:02:55.712182 39329 init.cc:234]     @     0x7f72814c0c4d clone
W1225 12:02:55.713292 39329 init.cc:234]     @                0x0 (unknown)
/opt/_internal/cpython-2.7.15-ucs4/lib/python2.7/site-packages/paddle/fluid/clip.py:779: UserWarning: Caution! 'set_gradient_clip' is not recommended and may be deprecated in future! We recommend a new strategy: set 'grad_clip' when initializing the 'optimizer'. This method can reduce the mistakes, please refer to documention of 'optimizer'.
  warnings.warn("Caution! 'set_gradient_clip' is not recommended "
2020-12-25 12:05:19,414-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
loading annotations into memory...
Done (t=0.91s)
creating index...
index created!
2020-12-25 12:05:26,709-INFO: places would be ommited when DataLoader is not iterable


API is deprecated since 2.0.0 Please use FleetAPI instead.
WIKI: https://github.com/PaddlePaddle/Fleet/blob/develop/markdown_doc/transpiler

        
W1225 12:05:26.929201 39460 device_context.cc:252] Please NOTE: device: 6, CUDA Capability: 70, Driver API Version: 10.2, Runtime API Version: 10.0
W1225 12:05:26.935179 39460 device_context.cc:260] device: 6, cuDNN Version: 7.6.
I1225 12:05:30.206835 39653 grpc_server.cc:477] Server listening on 127.0.0.1:11901 successful, selected port: 11901
2020-12-25 12:05:35,656-WARNING: /root/.cache/paddle/weights/ResNet50_vd_ssld_pretrained.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
/opt/_internal/cpython-2.7.15-ucs4/lib/python2.7/site-packages/paddle/fluid/io.py:1998: UserWarning: This list is not set, Because of Paramerter not found in program. There are: fc_0.b_0 fc_0.w_0
  format(" ".join(unused_para_list)))
loading annotations into memory...
Done (t=5.33s)
creating index...
index created!
2020-12-25 12:05:50,173-INFO: places would be ommited when DataLoader is not iterable
I1225 12:05:51.968932 39460 build_strategy.cc:361] set enable_sequential_execution:1
W1225 12:05:53.008332 39460 fuse_all_reduce_op_pass.cc:74] Find all_reduce operators: 276. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 172.
